export const cmdMap: Record<string, string> = {
  // lowercase greek
  alpha: "α",
  beta: "β",
  gamma: "γ",
  delta: "δ",
  epsilon: "ϵ",
  varepsilon: "ε",
  zeta: "ζ",
  eta: "η",
  theta: "θ",
  vartheta: "ϑ",
  iota: "ι",
  kappa: "κ",
  lambda: "λ",
  mu: "μ",
  nu: "ν",
  xi: "ξ",
  pi: "π",
  rho: "ρ",
  varrho: "ϱ",
  sigma: "σ",
  varsigma: "ς",
  tau: "τ",
  upsilon: "υ",
  phi: "φ",
  varphi: "ϕ",
  chi: "χ",
  psi: "ψ",
  omega: "ω",

  // uppercase greek
  Gamma: "Γ",
  Delta: "Δ",
  Theta: "Θ",
  Lambda: "Λ",
  Xi: "Ξ",
  Pi: "Π",
  Sigma: "Σ",
  Upsilon: "Υ",
  Phi: "Φ",
  Psi: "Ψ",
  Omega: "Ω",

  // common symbols
  nabla: "∇",
  bigtriangledown: "▽",
  triangleup: "△",
  triangleleft: "◁",
  triangleright: "▷",
  star: "⋆",
  partial: "∂",
  infty: "∞",
  times: "×",
  cdot: "·",
  pm: "±",
  mp: "∓",
  leq: "≤",
  geq: "≥",
  approx: "≈",
  simeq: "≃",
  neq: "≠",
  subset: "⊆",
  supset: "⊇",
  because: "∵",
  therefore: "∴",
  degree: "°",
  cup: "∪",
  cap: "∩",
  sqcup: "⊔",
  sqcap: "⊓",
  gets: "←",
  mapsfrom: "↦",
  maps: "↣",
  mapsup: "↥",
  mapsdown: "↧",
  mapsto: "↦",
  to: "→",
  longleftarrow: "←",
  longrightarrow: "→",
  leftrightarrow: "↔",
  updownarrow : "↕",
  Leftarrow: "⇐",
  Rightarrow: "⇒",
  Leftrightarrow: "⇔",  

  // trigonometric functions
  sin: "sin",
  cos: "cos",
  tan: "tan",
  cot: "cot",
  sec: "sec",
  csc: "csc",
  
  // inverse trigonometric functions
  arcsin: "arcsin",
  arccos: "arccos",
  arctan: "arctan",
  // arcctg is less common, using text notation
  // arcsec and arccsc are also less common
  
  // hyperbolic functions
  sinh: "sinh",
  cosh: "cosh",
  tanh: "tanh",
  coth: "coth",
  
  // inverse hyperbolic functions
  // Using text notation for these as well
  
  // logarithms and exponentials
  ln: "ln",
  log: "log",
  exp: "exp",
  
  // other mathematical functions
  max: "max",
  min: "min",
  det: "det",
  dim: "dim",
  ker: "ker",
  deg: "deg",
  gcd: "gcd",
  Pr: "Pr",
  arg: "arg",
  inf: "inf",
  lim: "lim",
  liminf: "liminf",
  limsup: "limsup",
  sup: "sup",
  
  // add more as needed
};